os: linux

language: go

go:
  - 1.13.x

env:
  global:
    - GO111MODULE=on

install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install make zip; fi
  - go get ./...

script:
  - echo ">>> Run build"
  - go env GOOS
  - go env GOARCH
  - make build
  - make pack_artifacts

builds: &builds
  stage: build

jobs:
  include:
    - <<: *builds
      os: osx
      osx_image: xcode11.3
    - <<: *builds
      os: windows
    - <<: *builds
      os: linux
    - stage: deploy
      script: skip
      deploy:
        - provider: releases
          skip_cleanup: true
          github-token: $GITHUB_TOKEN
          file_glob: true
          file: artifacts/**
          on:
            tags: true
            condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+