os: linux

language: go

go:
  - 1.13.x

env:
  global:
    - GO111MODULE=on

install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install make zip; fi
  - go get ./...

script:
  - echo ">>> Run build"
  - go env GOOS
  - go env GOARCH
  - make build
  - make pack_artifacts

builds: &builds
  stage: build

deploys: &deploys
  deploy:
    - provider: releases
      skip_cleanup: true
      api_key: $GITHUB_TOKEN
      file_glob: true
      file: artifacts/**
      on:
        tags: true

jobs:
  include:
    - <<: *builds
      os: osx
      osx_image: xcode11.3
      <<: *deploys
    - <<: *builds
      os: windows
      <<: *deploys
    - <<: *builds
      os: linux
      <<: *deploys