os: linux

language: go

go:
  - 1.13.x

env:
  global:
    - GO111MODULE=on

cmake: 3.15

before_install:
  - go get ./...

script:
  - echo ">>> Run build"
  - go env GOOS
  - make build

builds: &builds
  stage: build

jobs:
  include:
    - <<: *builds
      os: osx
      osx_image: xcode11.3
    - <<: *builds
      os: windows
    - <<: *builds
      os: linux