os: linux

language: go

go:
  - 1.13.x

env:
  global:
    - GO111MODULE=on

before_install:
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then; choco install make; fi
  - go get ./...

script:
  - echo ">>> Run build"
  - go env GOOS
  - make build

builds: &builds
  stage: build

jobs:
  include:
    - <<: *builds
      os: osx
      osx_image: xcode11.3
    - <<: *builds
      os: windows
    - <<: *builds
      os: linux