language: go

go: stable
cmake: 3.15

before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - go get ./...
  - GO111MODULE=on go install github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - go test ./...

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
