os: linux

language: go

go: master
cmake: 3.15

before_install:
  - go get ./...

script:
  - echo ">>> Run build"
  - make build

builds: &builds
  stage: build

jobs:
  include:
    - <<: *builds
      os: osx
    - <<: *builds
      os: windows